language: python
env:
 - TOXENV=py27 BLUEFLOOD_URL=$BLUEFLOOD_URL AUTH_USER_NAME=$AUTH_USER_NAME AUTH_TENANT=$AUTH_TENANT AUTH_API_KEY=$AUTH_API_KEY
install:
  - travis_retry pip install tox==1.6.1
script:
  - tox
